apiVersion: v1
kind: Namespace
metadata:
  name: application-aws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-python
  namespace: application-aws
  labels:
    app: hello-world-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-python
  template:
    metadata:
      labels:
        app: hello-world-python
    spec:
      containers:
      - name: hello-world-python
        image: localhost:32000/hello-world-python:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: aws-credentials
          mountPath: /tmp/aws/
          # readonly: true
        env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /tmp/aws/creds
        - name: AWS_REGION
          value: eu-west-1
        - name: AWS_DEFAULT_REGION
          value: eu-west-1
      volumes:
      - name: aws-credentials
        secret:
          secretName: aws-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-python
  namespace: application-aws
spec:
  type: NodePort
  selector:
    app: hello-world-python
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-headless
  namespace: application-aws
spec:
  clusterIP: None
  selector:
    app: hello-world-python
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
