apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
  namespace: application
  labels:
    app: hello-world-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
      - name: hello-world-service
        image: localhost:32000/hello-world-service:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: application
spec:
  type: NodePort
  selector:
    app: hello-world-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-headless
  namespace: application
spec:
  clusterIP: None
  selector:
    app: hello-world-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
