apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  ingress:
    kourier:
      enabled: true
  config:
    deployment:
      registries-skipping-tag-resolving: "ko.local,dev.local,localhost:32000"
    domain:
      svc.kn: ""
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
---
apiVersion: v1
kind: Service
metadata:
  name: kourier-np
  namespace: knative-serving
  labels:
    networking.knative.dev/ingress-provider: kourier
spec:
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 31080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
    nodePort: 31443
  selector:
    app: 3scale-kourier-gateway
  type: NodePort
