apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-world
  namespace: application
spec:
  template:
    spec:
      containers:
      - image: localhost:32000/hello-world-service:latest
        ports:
          - containerPort: 3000
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
